################################################################################
# Compiling Instructions
################################################################################
CC=	clang
CFLAGS=	-Wall -g -c
CFLAGS_LLVM= -Wall -g `llvm-config --cflags` -c
LD=clang++
LDFLAGS=`llvm-config --cxxflags --ldflags --libs core executionengine mcjit interpreter analysis native bitwriter --system-libs`

BISON= bison
FLEX= flex

################################################################################
# Source codes, Object files, and temporary files
################################################################################

# Source codes and object files in C
src= $(filter-out src/llvm.c, $(wildcard src/*.c))
obj= $(patsubst %.c,%.o, $(notdir $(src)))
temp= $(wildcard temp/*.*)
# Flex and Bison source file
yy=	src/parser.y
ll= src/scanner.l
# Temporary files generated by Flex and Bison
tmp_src= temp/bison.c temp/flex.c
tmp_obj= $(patsubst %.c,%.o, $(notdir $(tmp_src)))
# The LLVM source code and object file
llvm_src= src/llvm.c
llvm_obj= llvm.o
# The Executable
exe= bin/ekcc

SOURCE_LLVM= src/llvm.c
#= $(filter-out llvm.o, $(wildcard *.o))
OBJECT_LLVM= llvm.o

################################################################################
# Commands
################################################################################

all: \
	parser \
	scanner \
	project.o \
	llvm.o \
	main

parser: $(yy)
	${BISON} $(yy)

scanner: $(ll)
	${FLEX} $(ll)

project.o: $(src) $(tmp_src)
	${CC} ${CFLAGS} $(src) $(tmp_src)

llvm.o:	$(llvm_src)
	${CC} ${CFLAGS_LLVM} $(llvm_src)

main: $(obj) $(tmp_obj) $(llvm_obj)
	${LD} ${LDFLAGS} -o bin/ekcc $(obj) $(tmp_obj) $(llvm_obj)
	rm -f $(obj) $(tmp_obj) $(llvm_obj)

################################################################################
# Tests
################################################################################
test1:
	$(exe) -emit-ast -o ./tests/test91.yaml ./tests/test91.ek
test2:
	$(exe) -emit-ast -o ./tests/test92.yaml ./tests/test92.ek
ctest1:
	$(exe) -emit-ast -o ./tests/test01.yaml ./tests/test01.ek

################################################################################
# Housekeeping
################################################################################
clean:
	rm -f $(exe) ./testcases/*.yaml ./testcases/*.ast $(temp)
